#pragma once
#include <stdint.h>
#include <stddef.h>
#include "terminal.h"
#include "hal.h"
#include "gdt.h"
#include "memory/pmm.h"
#include "pic.h"
#include "pit.h"
#include "ps2.h"
#include "interrupts.h"
#include "pci.h"
#include "rtc.h"
#include "storage/ahci.h"
#include "storage/drive.h"